# Generated by Django 6.0.4 on 2026-05-18 08:04

import django.db.models.deletion
import utils.management
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_alter_gradethreshold_unique_together'),
        ('task_ws', '0006_finalize_widget_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompilerExplorerWidgetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('rows', models.PositiveSmallIntegerField(default=20, help_text='Number of rows in the terminal view (determines widget height)')),
                ('compiler', models.CharField(default='g152', help_text='Compiler identifier for Compiler Explorer. Default is g152 (gcc 15.2). See https://godbolt.org/api/compilers for options.', max_length=255)),
                ('default_stdin', models.TextField(blank=True, default='', help_text='Default input for the compiler stdin', max_length=1024)),
                ('compiler_args', models.CharField(blank=True, default='-std=c++17', help_text='Default compiler arguments', max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            bases=(models.Model, utils.management.ExportImportMixin),
        ),
    ]
